version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
        environment:
          APP_ENV: local
          APP_DEBUG: true
          DB_CONNECTION: sqlite

    working_directory: ~/textbox

    steps:
      - checkout

      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo composer install
      - run: cp .env.sqlite.exmple .env
      - run: php artisan key:generate
      - run: touch database/database.sqlite

      - run: php artisan migrate
      - run: npm install

      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true
      - run: php vendor/bin/phpunit
